//----------------------------------------------------------------------------------------------------------------------
/*!
   \file
   \brief       Definition of openSYDE communication stack configuration structures with their messages and signals.
   \copyright   Copyright 2017 Sensor-Technik Wiedemann GmbH. All rights reserved.
*/
//----------------------------------------------------------------------------------------------------------------------
#ifndef OSY_COM_CONFIGURATIONH
#define OSY_COM_CONFIGURATIONH

/* -- Includes ------------------------------------------------------------------------------------------------------ */
#include "stwtypes.h"
#include "osy_dpa_data_pool.h"
#include "osy_com_trg_if.h"

/* -- Defines ------------------------------------------------------------------------------------------------------- */
#ifdef __cplusplus
extern "C"
{
#endif

#define OSY_COM_CONFIG_MAGIC    (0xC011U) ///< "C011unication"

//Version of structure layout of COMM definition.
//Used for checking whether the structure of autogenerated code matches the expectations of the implementation.
//COMM definition version "3" corresponds to overall code structure version "3", "4" or "5" as selected in the openSYDE
// tool.
#define OSY_COM_CONFIG_DEFINITION_VERSION (0x0003U)

#define OSY_COM_DRIVER_IS_SAFE     (0x5AFEU) //may be used in safe context
#define OSY_COM_DRIVER_IS_NON_SAFE (0x0000U) //may not be used in safe context

#define OSY_COM_DRIVER_UNUSED_BITS_FILL_ZEROES (0x00U) //fill unused bits with zeroes when sending
#define OSY_COM_DRIVER_UNUSED_BITS_FILL_ONES   (0xFFU) //fill unused bits with ones when sending

#define OSY_COM_BYTE_ORDER_LITTLE   (0U)
#define OSY_COM_BYTE_ORDER_BIG      (1U)

#define OSY_COM_COMM_METHOD_CYCLIC              (0U) ///< message is transferred cyclically
#define OSY_COM_COMM_METHOD_ON_CHANGE           (1U) ///< message is transferred on change (with min/max time window)
#define OSY_COM_COMM_METHOD_ON_EVENT            (2U) ///< message is transferred on application call only

#define OSY_COM_IS_RX      (0U)
#define OSY_COM_IS_TX      (1U)

///message status
///message active/inactive
#define OSY_COM_MESSAGE_STATUS_INACTIVE             (0U) ///< message not supervised for Rx/Tx
#define OSY_COM_MESSAGE_STATUS_ACTIVE               (1U) ///< message supervised for Rx/Tx

///message send/receive status:
#define OSY_COM_MESSAGE_STATUS_TX_NOT_SENT          (0U) ///< data not sent yet
#define OSY_COM_MESSAGE_STATUS_TX_SENT              (1U) ///< data sent at least once
#define OSY_COM_MESSAGE_STATUS_TX_SEND_ERROR        (2U) ///< data send error/overflow
#define OSY_COM_MESSAGE_STATUS_TX_SEND_REQUESTED    (3U) ///< data send requested for sending on next Tx cycle

#define OSY_COM_MESSAGE_STATUS_RX_INIT              (3U) ///< data not yet received (data not valid)
#define OSY_COM_MESSAGE_STATUS_RX_NEW_DATA          (4U) ///< new data received (data valid)
#define OSY_COM_MESSAGE_STATUS_RX_NO_NEW_DATA       (5U) ///< data previously received, status cleared (data valid)
#define OSY_COM_MESSAGE_STATUS_RX_NEW_DATA_OVERFLOW (6U) ///< new data received with overflow (data valid)
#define OSY_COM_MESSAGE_STATUS_RX_TIMEOUT           (7U) ///< expected maximum time interval exceeded (data not valid)

///message last protocol error:
#define OSY_COM_MESSAGE_ERROR_RX_NO_ERROR           (0U) ///< no error occurred or previously cleared
#define OSY_COM_MESSAGE_ERROR_RX_DLC_ERROR          (1U) ///< CAN DLC error
#define OSY_COM_MESSAGE_ERROR_RX_SEQUENCE_ERROR     (2U) ///< ECeS: message sequence counter error;
///< ECoS: frame sequence error
#define OSY_COM_MESSAGE_ERROR_RX_CRC_ERROR          (3U) ///< ECeS only: message with invalid CRC received
#define OSY_COM_MESSAGE_ERROR_RX_DATA_ERROR         (4U) ///< ECoS only: frame data congruency error

/* -- Types --------------------------------------------------------------------------------------------------------- */

///Definition of one comm signal
typedef struct
{
   uint8 u8_ByteOrder;              ///< 0 = little endian; 1 = big endian
   uint8 u8_BitStart;               ///< Bit start position (0..63)
   uint8 u8_BitSize;                ///< Size of signal in bits (1..64)
   uint16 u16_DataPoolListIndex;    ///< mapped data pool list
   uint16 u16_DataPoolElementIndex; ///< mapped data pool element
} T_osy_com_signal_definition;

//----------------------------------------------------------------------------------------------------------------------

///Definition of one multiplexed "set" of message (or the "single" set if the message is not multiplexed)
typedef struct
{
   uint16 u16_MuxValue;      ///< multiplexer value (not used for non-mux)
   uint8 u8_NumberOfSignals; ///< number of signals in this message (including the
   ///< multiplexer signal)
   const T_osy_com_signal_definition * pt_Signals; ///< table of signals in this multiplexed messages
   ///< if muxed: mux must be first entry
} T_osy_com_message_mux_definition;

//----------------------------------------------------------------------------------------------------------------------

///Status of on multiplexed message (or the single message if the message is not multiplexed)
typedef struct
{
   uint32 u32_LastTransferTimeRx; ///< For RX: last time the message was correctly received and the
   ///< data pool data updated
   uint8 u8_LastProtocolError; ///< RX only: last transmission error based on protocol
   uint8 u8_Status;            ///< transmission or reception status of message
} T_osy_com_message_mux_status;

//----------------------------------------------------------------------------------------------------------------------

///Definition of one comm message
typedef struct
{
   uint32 u32_MessageId;               ///< CAN message identifier
   uint8 u8_MessageIdExt;              ///< 0 = 11bit ID; 1 = 29bit ID
   uint8 u8_MessageDlc;                ///< data length code 0..8 in bytes (payload only)
   uint8 u8_CommMethod;                ///< transfer trigger (see OSY_COM_COMM_METHOD_* definitions)
   uint8 u8_MessageCounterGap;         ///< ECeS only: number of accepted missing messages
   uint16 u16_ChangeMinimumIntervalMs; ///< For cyclic, event driven and change driven RX: not used
   ///< For change driven TX: minimum interval between sending (even if changed)
   uint16 u16_MaximumIntervalMs; ///< For cyclic TX: message transmission interval
   ///< For cyclic RX: maximum permitted reception interval
   ///< For change driven: maximum interval between sending (even if no change)
   ///< For event driven RX: optional maximum permitted reception interval. When set to 0 no reception interval defined
   uint16 u16_NumMuxedMessages; ///< number of muxed message instances (equals to length of tables)
   ///< 0: not muxed
   T_osy_com_message_mux_status * pt_MessageMuxStatus; ///< table with status of muxed messages
   ///< for non-muxed messages: points to just one entry
   const T_osy_com_message_mux_definition * pt_MuxedMessages; ///< table with definitions of muxed messages
   ///< (if not muxed: just one entry)
} T_osy_com_message_definition;

//----------------------------------------------------------------------------------------------------------------------

///Status of message at run-time
typedef struct
{
   uint32 u32_TimeStampFirstFrame; ///< ECoS only: Time the first frame was received
   uint32 u32_LastTransferTimeTx;  ///< For TX: last time the message was passed to CAN driver
   uint16 u16_NextTxMuxIndex;      ///< For TX cyclic: index of next MUX to send (so we can "autoadvance")
   uint8 u8_MessageCounter;        ///< ECeS only: Last sent or next expected message counter
   uint8 u8_Active;                ///< 0: inactive; do not supervise reception; do not send in cyclic TX function
   ///< 1: active; supervise reception; send in cyclic TX function
   uint8 au8_Data[8]; ///< For change-driven TX CL2: last sent data
   ///< For ECoS Rx: data of the first message
} T_osy_com_message_status;

//----------------------------------------------------------------------------------------------------------------------

///Definition of messages of one protocol type on one communication bus
typedef struct
{
   uint16 u16_MagicMark;     ///< To identify proper configuration instances.
   uint16 u16_LayoutVersion; ///< Version of the layout of the protocol
   ///< configuration and subordinate elements.
   uint16 u16_NumTxMessages;                           ///< Number of defined TX messages
   uint16 u16_NumRxMessages;                           ///< Number of defined RX messages
   const T_osy_com_message_definition * pt_TxMessages; ///< Table of all defined TX messages
   ///< Points to an array with NumTxMessages entries.
   const T_osy_com_message_definition * pt_RxMessages; ///< Table of all defined RX messages.
   ///< Points to an array with NumRxMessages entries.
   T_osy_com_message_status * pt_TxMessagesStatus; ///< Table of run-time instance data for all
   ///< defined TX messages.
   T_osy_com_message_status * pt_RxMessagesStatus; ///< Table of run-time instance data for all
   ///< defined RX messages.
   const T_osy_dpa_data_pool * pt_SignalDataPool; ///< References data pool that contains all
   ///< signals used by the signal definitions.
} T_osy_com_protocol_definition;

//----------------------------------------------------------------------------------------------------------------------

///Definition of comm driver functions
typedef sint16 (* PR_osy_com_verify_definition)(const T_osy_com_protocol_definition * const opt_ProtocolDefinition);
typedef sint16 (* PR_osy_com_compose_tx_message)(const uint8 ou8_CanChannel,
                                                 T_osy_com_trg_can_message * const opt_CanMessage,
                                                 T_osy_com_message_status * const opt_TxMessageStatus);
typedef sint16 (* PR_osy_com_handle_control_rx_message)(const T_osy_com_trg_can_message * const opt_CanMessage,
                                                        const uint8 ou8_CanChannel,
                                                        const T_osy_com_protocol_definition * const
                                                        opt_ProtocolDefinition);
typedef sint16 (* PR_osy_com_decompose_rx_message)(const T_osy_com_trg_can_message * const opt_CanMessage,
                                                   const T_osy_com_message_definition * const opt_RxMessage,
                                                   T_osy_com_message_status * const opt_RxMessageStatus,
                                                   uint8 opu8_Data[8]);
typedef sint16 (* PR_osy_com_handle_rx_message_status)(const T_osy_com_trg_can_message * const opt_CanMessage,
                                                       const T_osy_com_message_definition * const opt_RxMessage,
                                                       T_osy_com_message_status * const opt_RxMessageStatus,
                                                       T_osy_com_message_mux_status * const opt_RxMessageMuxStatus);
typedef void (* PR_osy_com_handle_protocol_tasks)(const uint8 ou8_IsTx, const uint8 ou8_CanChannel);

//----------------------------------------------------------------------------------------------------------------------

///Definition of comm driver interface
typedef struct
{
   PR_osy_com_verify_definition pr_VerifyDefinition;
   PR_osy_com_compose_tx_message pr_ComposeTxMessage;
   PR_osy_com_handle_control_rx_message pr_HandleControlRxMessage;
   PR_osy_com_decompose_rx_message pr_DecomposeRxMessage;
   PR_osy_com_handle_rx_message_status pr_HandleRxMessageStatus;
   PR_osy_com_handle_protocol_tasks pr_HandleProtocolTasks;
   uint16 u16_ProvidesSafeImplementation; ///< see OSY_COM_DRIVER_IS_* defines
   uint8 u8_FillValueForUnusedBits;       ///< see OSY_COM_DRIVER_UNUSED_BITS_FILL_* defines
} T_osy_com_driver;

//----------------------------------------------------------------------------------------------------------------------

///Describes used CAN channel and protocol type with according protocol definition
/// and holds protocol type specific function pointers.
typedef struct
{
   uint8 u8_CanChannel;
   uint8 u8_ProtocolType;
   T_osy_com_protocol_definition t_ProtocolDefinition;
   const T_osy_com_driver * pt_Driver;
} T_osy_com_protocol_configuration;

/* -- Global Variables ---------------------------------------------------------------------------------------------- */

/* -- Function Prototypes ------------------------------------------------------------------------------------------- */

/* -- Implementation ------------------------------------------------------------------------------------------------ */

#ifdef __cplusplus
} //end of extern "C"
#endif

#endif
